### ISSUE TITLE
Problem with language calculation

### ISSUE THREAD

**Issue by elunico** [elunico/guppy#1]
when running `./guppy.py repo processing/p5.js` the following error occurs 

```
Traceback (most recent call last):
  File "./guppy.py", line 50, in <module>
    main()
  File "./guppy.py", line 46, in main
    dispatch()
  File "./guppy.py", line 40, in dispatch
    info_repo(*sys.argv[2:])
  File "/home/thomas/Dropbox/Ubuntu/CodeProjects/PersonalProjects/guppy/repo_display.py", line 149, in info_repo
    RepoLanguageInfoDisplayObject(repo_info).display()
  File "/home/thomas/Dropbox/Ubuntu/CodeProjects/PersonalProjects/guppy/repo_display.py", line 55, in display
    total = sum([lines for (lang, lines) in langs.items()])
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by elunico** [comment]
This was because I got rate limited in between the repo info and the language info and the language info display didn't check for errors in response.
